/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package swin.chat;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_menu_exit=0x7f020000;
        public static final int icon=0x7f020001;
    }
    public static final class id {
        public static final int btnConnect=0x7f06000e;
        public static final int btnRefresh=0x7f060010;
        public static final int btnSend=0x7f060003;
        public static final int btnSkip=0x7f060009;
        public static final int item_logout=0x7f060013;
        public static final int lblServer=0x7f06000a;
        public static final int lblUser=0x7f06000c;
        public static final int linearLayout1=0x7f060001;
        public static final int listChat=0x7f060000;
        public static final int listOtherUser=0x7f06000f;
        public static final int progressBar1=0x7f060007;
        public static final int row_icon=0x7f060011;
        public static final int row_label=0x7f060012;
        public static final int row_lblMessage=0x7f060005;
        public static final int row_lblUser=0x7f060004;
        public static final int textView1=0x7f060006;
        public static final int txtMessage=0x7f060002;
        public static final int txtProgress=0x7f060008;
        public static final int txtServer=0x7f06000b;
        public static final int txtUser=0x7f06000d;
    }
    public static final class layout {
        public static final int chat=0x7f030000;
        public static final int chat_list_row=0x7f030001;
        public static final int greet=0x7f030002;
        public static final int login=0x7f030003;
        public static final int main=0x7f030004;
        public static final int otheruser=0x7f030005;
        public static final int otheruserlistrow=0x7f030006;
        public static final int settings=0x7f030007;
    }
    public static final class menu {
        public static final int main_menu=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
