/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.googlecode.chartdroid.example.minimal;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int calheader=0x7f020000;
        public static final int current_day=0x7f020001;
        public static final int dayinmonth=0x7f020002;
        public static final int event=0x7f020003;
        public static final int icon=0x7f020004;
        public static final int left_arrow=0x7f020005;
        public static final int rectgrad=0x7f020006;
        public static final int right_arrow=0x7f020007;
        public static final int selectedgrad=0x7f020008;
    }
    public static final class id {
        public static final int button_sample_datasets=0x7f050000;
        public static final int imgLeft=0x7f050001;
        public static final int imgRight=0x7f050004;
        public static final int txtDay=0x7f050002;
        public static final int txtYear=0x7f050003;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int monthtop=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
